(require 'helm-config)
(helm-mode 1)
(helm-descbinds-mode 1)
(setq helm-split-window-default-side 'right)
(require 'helm-ag)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-x f") 'helm-mini)
(global-set-key (kbd "C-c C-f") 'helm-find-files)
(global-set-key (kbd "C-c s") 'helm-ag)
(global-set-key (kbd "M-y")     'helm-show-kill-ring)
(global-set-key (kbd "C-c i")   'helm-imenu)
(global-set-key (kbd "C-x b")   'helm-buffers-list)
(define-key helm-map (kbd "C-h") 'delete-backward-char)
(global-set-key (kbd "M-o") 'helm-occur)
(define-key isearch-mode-map (kbd "C-o") 'helm-occur-from-isearch)
(define-key helm-map (kbd "C-c C-a") 'all-from-helm-occur)
(setq helm-css-scss-split-direction 'split-window-horizontally)
;;(global-set-key (kbd "C-c C-;") 'ac-complete-with-helm)
;;(define-key ac-complete-mode-map (kbd "C-c C-;") 'ac-complete-with-helm)

;; Disable helm in some functions
(setq helm-delete-minibuffer-contents-from-point t)
(add-to-list 'helm-completing-read-handlers-alist '(find-alternate-file . nil))
(defadvice helm-delete-minibuffer-contents (before helm-emulate-kill-line activate)
  (kill-new (buffer-substring (point) (field-end))))
(define-key helm-find-files-map (kbd "TAB") 'helm-execute-persistent-action)
(define-key helm-read-file-map (kbd "TAB") 'helm-execute-persistent-action)
